# Generated by Django 5.1.1 on 2024-10-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headmate',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pronouns', models.CharField(max_length=25)),
                ('age', models.IntegerField(default=0)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('display', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Fantasia Collective', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('site_info', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
