# Generated by Django 5.1.1 on 2024-10-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
