# Generated by Django 5.1.1 on 2024-10-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_siteconfig_last_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='site_info',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='site_name',
            new_name='name',
        ),
    ]
