# Generated by Django 5.1.1 on 2024-10-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_rename_site_info_siteconfig_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmate',
            name='image',
            field=models.ImageField(upload_to='media/headmates'),
        ),
    ]
