# Generated by Django 5.1.1 on 2024-10-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_headmate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmate',
            name='image',
            field=models.ImageField(upload_to='headmates'),
        ),
    ]
