# Generated by Django 5.1.1 on 2024-10-04 05:41

import info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_alter_headmate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='info',
            new_name='header_info',
        ),
        migrations.AddField(
            model_name='headmate',
            name='icon',
            field=models.ImageField(blank=True, upload_to=info.models.Headmate.file_directory),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='footer_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='age',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='image',
            field=models.ImageField(upload_to=info.models.Headmate.file_directory),
        ),
    ]
