# Generated by Django 5.1.1 on 2024-10-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_rename_info_siteconfig_header_info_headmate_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='header_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
