# Generated by Django 5.1.1 on 2024-10-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_siteconfig_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headmate',
            old_name='icon',
            new_name='Icon',
        ),
        migrations.RenameField(
            model_name='headmate',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='header_image',
            new_name='Header Image',
        ),
        migrations.AddField(
            model_name='headmate',
            name='Image Source',
            field=models.URLField(blank=True),
        ),
    ]
