# Generated by Django 5.1.1 on 2024-10-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_rename_icon_headmate_icon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headmate',
            old_name='Icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='headmate',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='headmate',
            old_name='Image Source',
            new_name='image_source',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='Header Image',
            new_name='image',
        ),
    ]
