# Generated by Django 5.1.1 on 2024-10-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0009_rename_icon_headmate_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmate',
            name='colour',
            field=models.CharField(blank=True, max_length=7, verbose_name='Hex Colour Code'),
        ),
    ]
