# Generated by Django 5.1.1 on 2024-10-05 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_headmate_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='header_info',
            field=models.TextField(blank=True),
        ),
    ]
