# Generated by Django 5.1.1 on 2024-10-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_alter_siteconfig_header_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmate',
            name='order',
            field=models.SmallIntegerField(blank=True, default=1, max_length=2, verbose_name='Sort order'),
            preserve_default=False,
        ),
    ]
