# Generated by Django 5.1.1 on 2024-10-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0012_headmate_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headmate',
            name='colour',
        ),
        migrations.AddField(
            model_name='headmate',
            name='bg_colour',
            field=models.CharField(blank=True, max_length=7, verbose_name='Background hexidecimal colour code'),
        ),
        migrations.AddField(
            model_name='headmate',
            name='border_colour',
            field=models.CharField(blank=True, max_length=7, verbose_name='Border hexidecimal colour code'),
        ),
        migrations.AddField(
            model_name='headmate',
            name='custom_colour_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='order',
            field=models.SmallIntegerField(blank=True, verbose_name='Sort order'),
        ),
    ]
