# Generated by Django 5.1.1 on 2024-10-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0013_remove_headmate_colour_headmate_bg_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmate',
            name='custom_colour_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable custom colours?'),
        ),
    ]
