# Generated by Django 5.1.1 on 2024-10-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0014_alter_headmate_custom_colour_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headmate',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Show headmate?'),
        ),
    ]
