# Generated by Django 5.1.1 on 2024-10-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0015_alter_headmate_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='headmate',
            name='shadow_colour',
            field=models.CharField(blank=True, max_length=7, verbose_name='Shadow hexidecimal colour code'),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='custom_colour_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable custom colours'),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='display',
            field=models.BooleanField(default=True, verbose_name='Show headmate'),
        ),
    ]
