# Generated by Django 5.1.1 on 2024-10-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_headmate_shadow_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='bg_colour',
            field=models.CharField(default=123456, max_length=7, verbose_name='Background hexidecimal colour code'),
            preserve_default=False,
        ),
    ]
