# Generated by Django 5.1.1 on 2024-10-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0017_siteconfig_bg_colour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='image',
            new_name='header_image',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='bg_colour',
            field=models.CharField(blank=True, help_text="Hexadecimal colour code, i.e., '#FF0000'.", max_length=7, verbose_name='Background colour'),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='border_colour',
            field=models.CharField(blank=True, help_text="Hexadecimal colour code, i.e., '#FF0000'.", max_length=7, verbose_name='Border colour'),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='display',
            field=models.BooleanField(default=True, help_text='Display this headmate on the frontend.', verbose_name='Show headmate'),
        ),
        migrations.AlterField(
            model_name='headmate',
            name='shadow_colour',
            field=models.CharField(blank=True, help_text="Hexadecimal colour code, i.e., '#FF0000'.", max_length=7, verbose_name='Shadow colour'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='bg_colour',
            field=models.CharField(help_text="Hexadecimal colour code, i.e., '#FF0000'.", max_length=7, verbose_name='Background colour'),
        ),
    ]
