# Generated by Django 5.1.1 on 2024-10-18 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0018_rename_image_siteconfig_header_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='maintenance_mode',
        ),
    ]
